# Generated by Django 5.2.4 on 2025-07-31 06:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_pagina_leida', models.PositiveIntegerField(verbose_name='Última página leída')),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de avance')),
                ('libro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progreso', to='libros.libro')),
            ],
        ),
    ]
