# Generated by Django 5.2.4 on 2025-08-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='porcentaje_avance',
            field=models.PositiveIntegerField(default=0, help_text='Porcentaje de avance de lectura (0-100)'),
        ),
    ]
