# Generated by Django 5.2.4 on 2025-08-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_libro_porcentaje_avance'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='libros_portadas/', verbose_name='Portada'),
        ),
    ]
