# Generated by Django 5.2.4 on 2025-07-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('libros_asociados', models.ManyToManyField(related_name='metas', to='libros.libro')),
            ],
        ),
    ]
