# Generated by Django 5.2.4 on 2025-08-02 01:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metalectura',
            name='usuarios_asignados',
            field=models.ManyToManyField(blank=True, help_text='Usuarios a los que se asigna esta meta', related_name='metas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metalectura',
            name='porcentaje_avance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
