# Generated by Django 5.2.4 on 2025-08-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0003_metalectura_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalectura',
            name='objetivo_libros',
            field=models.PositiveIntegerField(blank=True, help_text='Objetivo de libros leídos para esta meta', null=True),
        ),
        migrations.AddField(
            model_name='metalectura',
            name='objetivo_notas',
            field=models.PositiveIntegerField(blank=True, help_text='Objetivo de notas por libro para esta meta', null=True),
        ),
    ]
